<?php

function tripogater_preprocess_html(&$variables) {
  // Get currently active user and his roles.
  $account = \Drupal::currentUser();
  $roles = $account->getRoles();
  // The getRoles() method will return us the machine names, so there is no need
  // to process roles names additionally. However, I suggest prefixing the names
  // with "role-", so it's more obvious.
  foreach ($roles as $role) {
    $variables['attributes']['class'][] = 'role-' . $role;
  }
}
